<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/1/4
 * Time: 21:50
 */

namespace backend\filters;


use yii\base\ActionFilter;
use yii\web\HttpException;

class CheckFilter extends ActionFilter
{
    public function beforeAction($action)
    {
        //return false;
        if (!\Yii::$app->user->can($action->uniqueId)) {

            throw new HttpException(403,"你没有权限访问");
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}